config/routes.rb
Rails.application.routes.draw do

	get 'trees/index'
	get 'trees/data', :defaults => { :format => 'json' }

  resources :relatives, :only => [:index, :create, :new, :update, :destroy, :show, :edit, :delete]

  resources :scrapbooks, :only => [:index, :create, :new, :update, :destroy, :show, :delete, :edit]

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  resources :users, :only => [:create, :new]
  
  root :to => 'welcome#index'

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
  :recoverable, :rememberable, :trackable, :validatable

  has_many :relatives
  has_one :scrapbook
end

app/models/relative.rb
class Relative < ActiveRecord::Base
	has_attached_file :image, styles: { :large => "600x600>", :medium => "300x300>", :thumb => "150x150#" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

	belongs_to :scrapbook
	belongs_to :user
	belongs_to :admin_user
	belongs_to :mother, class_name: "Relative"
	belongs_to :father, class_name: "Relative"
	
	def children
		Relative.where("mother_id = ? or father_id = ?", id, id)
	end
end

app/models/scrapbook.rb
class Scrapbook < ActiveRecord::Base
	belongs_to :user
	has_many :relatives, through: :user
end

app/models/tree.rb
class Tree < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :registerable, :recoverable, and :omniauthable
  devise :database_authenticatable, :rememberable, :trackable, :validatable, :authentication_keys => [:username]

  has_many :relatives
  has_one :scrapbook

  def email_required?
  	false
  end

  def email_changed?
  	false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  # def current_or_guest_user
  # 	if current_or_guest_user
  # 		if session[:guest_user_id] && session[:guest_user_id] != current_user.id
  # 			logging_in
  # 			guest_user(with_retry = false).try(:destroy)
  # 			session[:guest_user_id] = nil
  # 		end
  # 		current_user
  # 	else
  # 		guest_user
  # end
end

app/controllers/relatives_controller.rb
class RelativesController < ApplicationController
	# InheritedResources::Base

	def index
		@relatives = current_user.relatives.all
		respond_to do |format|
			format.html
			format.json { render :json => Relative.all }
		end
	end

	def show
		@relative = Relative.find(params[:id])
	end

	def new
		@relative = Relative.new
		@relatives = current_user.relatives.all
	end

	def edit
		@relative = Relative.find(params[:id])
	end

	def create
		new_relative = current_user.relatives.create(relative_params)

		redirect_to scrapbook_path(current_user.id)
	end

	def update
		relative = Relative.find(params[:id])
		relative.update(relative_params)

		redirect_to relatives_path
	end

	def destroy
		relative = Relative.find(params[:id])
		relative.destroy

		redirect_to scrapbook_path(current_user.id)
	end

	private

	def relative_params
		params.require(:relative).permit(:first_name, :last_name, :scrapbook_id, :addresss, :age, :birthday, :date_of_death, :father_id, :mother_id, :child_one, :child_two, :child_three, :child_four, :child_five, :child_six, :occupation, :biography, :user_id, :image)
	end

end

app/controllers/scrapbooks_controller.rb
class ScrapbooksController < ApplicationController
	before_action :set_scrapbook, only: [:show, :edit, :update, :destroy]

def index
	@scrapbooks = Scrapbook.all
		respond_to do |format|
			format.html { render :index }
			format.json {
				scrapbooks = Scrapbook.all
				render :json => scrapbooks
			}
		end
	end

	def new
		@scrapbook = Scrapbook.new
	end

	def create
		scrapbook = Scrapbook.create(scrapbook_params)
		# render :json => scrapbook
		redirect_to scrapbook_path(current_user.id)
	end

	def show
		@relatives = Relative.all
	end

	def update
		scrapbook.update(scrapbook_params)

		redirect_to scrapbook_path(current_user.id)
	end

	def edit
		@scrapbook = Scrapbook.find_by_user_id(current_user.id)
	end

	def destroy
		scrapbook.destroy

		redirect_to root_path	
	end

  private

    def scrapbook_params
      params.require(:scrapbook).permit(:name, :user_id, :relative_id)
    end

    def set_scrapbook
			@scrapbook = Scrapbook.find(params[:id])
    end
end

app/controllers/trees_controller.rb
class TreesController < ApplicationController

	def index
	end

	def data
		respond_to do |format|
			format.html { render :index }
			format.json { render :json => Relative.all }
		end
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		# Pry.start(binding)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relatives_helper.rb
module RelativesHelper
end

app/helpers/scrapbooks_helper.rb
module ScrapbooksHelper
end

app/helpers/trees_helper.rb
module TreesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Scrapbook</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>
<body>

	<% if current_user %>
	<h3 id="greeting">Welcome back, <%= current_user.username %> family! </h3>
	<% else %>
	<p id="login"> <%= link_to 'Login', new_user_session_path %> </p>
	<p id="link-new-rel"> <%= link_to 'Administrator Login', new_admin_user_session_path %> </p>
	<% end %>

	<% if current_user %>
	<button id="menu-button" type="button" class="js-menu-trigger sliding-panel-button">
		<h3 id="menu">Menu</h3>
	</button>

	<nav class="js-menu sliding-panel-content">
		<ul>
			<li> <%= link_to 'Home', root_path %> </li>
			<li> <%= link_to 'Scrapbook', scrapbook_path(current_user.id) %> </li>
			<% if current_user %>
			<li> <%= link_to 'Edit Scrapbook', edit_scrapbook_path(current_user.id) %> </li>
			<% end %>
			<li> <%= link_to 'Family Tree', trees_index_path %> </li>
			<li> <%= link_to 'Relatives', relatives_path %> </li>
			<% if current_user %>
			<li> <%= link_to 'Add Relatives', new_relative_path %> </li>
			<li> <%= link_to "Sign Out", destroy_user_session_path, method: 'DELETE'  %> </li>
			<% end %>
		</ul>
	</nav>
	<div class="js-menu-screen sliding-panel-fade-screen"></div>
	<% end %>

	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	<%= yield %>

</body>
</html>

app/views/relatives/_form.html.erb
<%= form_for @relative, html: { multipart: true } do |f| %>
<% if @relative.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@relative.errors.count, "error") %> prohibited this relative from being saved:</h2>

  <ul>
    <% @relative.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :first_name %><br>
  <%= f.text_field :first_name %>
</div>

<div class="field">
  <%= f.label :last_name %><br>
  <%= f.text_field :last_name %>
</div>

<div class="field">
  <%= f.label :age %><br>
  <%= f.text_field :age %>
</div>

<div class="field">
  <%= f.label :birthday %><br>
  <%= f.text_field :birthday %>
</div>

<div class="field">
  <%= f.label :father_id %><br>
  <%= f.collection_select :father_id, current_user.relatives.all, :id, :first_name, include_blank: true  %>
</div>

<div class="field">
  <%= f.label :mother_id %><br>
  <%= f.collection_select :mother_id, current_user.relatives.all, :id, :first_name, include_blank: true %>
</div>

<div class="field">
  <%= f.label :biography %><br>
  <%= f.text_area :biography %>
</div>

<div class="field">
  <%= f.label :image %><br>
  <%= f.file_field :image %>
</div>

<%= f.hidden_field :scrapbook_id, :value => current_user.id%>

<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/relatives/_relative.html.erb
<details>
<summary><%= relative.first_name %> <%= relative.last_name %></summary>
<%= image_tag @relative.image.url(:medium) %>
<blockquote><%= render relative.children %></blockquote>
</details>

app/views/relatives/edit.html.erb
<h1>Editing <%= @relative.first_name %> </h1>

<%= form_for @relative, html: { multipart: true } do |f| %>
<% if @relative.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@relative.errors.count, "error") %> prohibited this relative from being saved:</h2>

  <ul>
    <% @relative.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :first_name %><br>
  <%= f.text_field :first_name %>
</div>

<div class="field">
  <%= f.label :last_name %><br>
  <%= f.text_field :last_name %>
</div>

<div class="field">
  <%= f.label :age %><br>
  <%= f.text_field :age %>
</div>

<div class="field">
  <%= f.label :birthday %><br>
  <%= f.text_field :birthday %>
</div>

<div class="field">
  <%= f.label :father_id %><br>
  <%= f.collection_select :father_id, Relative.all, :id, :first_name, include_blank: true  %>
</div>

<div class="field">
  <%= f.label :mother_id %><br>
  <%= f.collection_select :mother_id, Relative.all, :id, :first_name, include_blank: true %>
</div>

<div class="field">
  <%= f.label :biography %><br>
  <%= f.text_area :biography %>
</div>

<div class="field">
  <%= f.label :image %><br>
  <%= f.file_field :image %>
</div>

<%= f.hidden_field :user_id, :value => current_user.id%>
<%= f.hidden_field :scrapbook_id, :value => current_user.id%>

<div class="actions">
  <%= f.submit %>
</div>
<% end %>

<%= link_to 'Show', @relative %> |
<%= link_to 'Back', scrapbook_path(current_user) %> |
<%= link_to 'Delete', { action: :destroy }, method: :delete, data: { confirm: 'Are you sure?' } %>

app/views/relatives/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Relatives of the <%=current_user.username%> family</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @relatives.each do |relative| %>
    <tr>
      <td> <%= relative.first_name %> <%= relative.last_name %> </td>
      <td> <%= link_to 'More', relative %> </td>
      <td> <%= link_to 'Delete', relative, method: :delete, data: { confirm: 'Are you sure?' } %> </td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>


<button> <%= link_to 'New Relative', new_relative_path %> </button>

app/views/relatives/new.html.erb
<h1>Add Relative</h1>

<%= render 'form' %>

<%= link_to 'Back', relatives_path %>

app/views/relatives/show.html.erb
<p id="notice"><%= notice %></p>

<%= render @relative %>

<%= link_to 'Edit', edit_relative_path(@relative) %> |
<%= link_to 'Back', scrapbook_path(current_user) %>

app/views/scrapbooks/_form.html.erb
<%= form_for(@scrapbook) do |f| %>
  <% if @scrapbook.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@scrapbook.errors.count, "error") %> prohibited this scrapbook from being saved:</h2>

      <ul>
      <% @scrapbook.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="field">
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</div>

<div class="field">
  <%= f.hidden_field :user_id, value: current_user.id %>
</div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/scrapbooks/edit.html.erb
<h1>Editing Scrapbook</h1>

<%= render 'form' %>

<%= link_to 'Show', @scrapbook %> |
<%= link_to 'Back', scrapbooks_path %>

app/views/scrapbooks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Scrapbooks</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @scrapbooks.each do |scrapbook| %>
      <tr>
        <td><%= link_to 'Show', scrapbook %></td>
        <td><%= link_to 'Edit', edit_scrapbook_path(scrapbook) %></td>
        <td><%= link_to 'Destroy', scrapbook, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Scrapbook', new_scrapbook_path %>

app/views/scrapbooks/new.html.erb
<h1>New Scrapbook</h1>

<%= render 'form' %>

<%= link_to 'Back', scrapbooks_path %>

app/views/scrapbooks/show.html.erb
<p id="notice"><%= notice %></p>

<div id="member">
	<% count = 1 %>
	<% @relatives.each do |relative| %>	
	<% if relative.user_id == current_user.id %>
	<div class="family-member">
		<div class="modal">
			<label for=<%= "modal-#{count}" %>>
				<div class="modal-trigger"><%= image_tag relative.image.url(:medium) %></div>
			</label>
			<input class="modal-state" id= <%= "modal-#{count}" %> type="checkbox" />
			<div class="modal-fade-screen">
				<div class="modal-inner">
					<label class="modal-close" for=<%= "modal-#{count}" %>></label>
					<p> <%= image_tag relative.image.url(:medium) %> </p>
					<h1><%= relative.first_name%> <%= relative.last_name %></h1>
					<p>Biography: <%= relative.biography %></p>
					<p>Birthday: <%= relative.birthday %></p>
				</div>
			</div>
		</div>
	</div>
	<% end %>
	<% count += 1 %>
	<% end %>
</div>

app/views/trees/_form.html.erb
<%= form_for(@tree) do |f| %>
  <% if @tree.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tree.errors.count, "error") %> prohibited this tree from being saved:</h2>

      <ul>
      <% @tree.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trees/edit.html.erb
<h1>Editing Tree</h1>

<%= render 'form' %>

<%= link_to 'Show', @tree %> |
<%= link_to 'Back', trees_path %>

app/views/trees/index.html.erb
<p id="notice"><%= notice %></p>

<%= javascript_include_tag "https://d3js.org/d3.v3.min.js" %>

<div id="area2">

</div>

app/views/trees/new.html.erb
<h1>New Tree</h1>

<%= render 'form' %>

<%= link_to 'Back', trees_path %>

app/views/trees/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tree_path(@tree) %> |
<%= link_to 'Back', trees_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<html>
<head>
	<style>
	body {
		background: url("https://i.imgur.com/6TgQWq4.png");
		background-size: cover;
	}		
	#login, label, a, #greeting {
		color: aliceblue;
	}
	#welcome-text {
		text-align: center;
		margin: 12.25% 20% 0 20%;
	}	
	</style>
	<title>Scrapbook</title>
</head>
<body>
	<div id="welcome-text">
		<h1 id="logo">Scrapbook</h1>
		<p id="text-welcome">Scrapbook is an online tool that allows families to keep tradition and culture alive for generations.  By building a scrapbook of your family's history, you are creating something that can be passed along to other members of your family no matter where they are in the world.  Get started today and begin preserving your family's legacy! </p>
	</div>
</body>
</html>